ALTER TABLE test 
    MODIFY name TEXT  CHARACTER SET utf8mb4 NOT NULL,
    MODIFY test_locator TEXT  CHARACTER SET utf8mb4 NOT NULL;

ALTER TABLE test_suite MODIFY name TEXT  CHARACTER SET utf8mb4 NOT NULL;