ALTER TABLE task MODIFY COLUMN remark VARCHAR(255) DEFAULT NULL;
ALTER TABLE git_users MODIFY COLUMN mask VARCHAR(16) NOT NULL DEFAULT 'mask';
ALTER TABLE repositories MODIFY COLUMN mask VARCHAR(16) NOT NULL DEFAULT 'mask';
