CREATE TABLE IF NOT EXISTS clone_token(
    id VARCHAR(32) NOT NULL,
    repo_id VARCHAR(32) NOT NULL,
    token VARCHAR(255) NOT NULL,
    active BOOLEAN DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE git_users ADD COLUMN  token VARCHAR(255) NOT NULL;
ALTER TABLE git_users ADD COLUMN refresh_token VARCHAR(255);
ALTER TABLE git_users ADD COLUMN token_expiry TIMESTAMP;
