ALTER TABLE task MODIFY COLUMN remark VARCHAR(1024) DEFAULT NULL;
ALTER TABLE git_users MODIFY COLUMN mask VARCHAR(32) NOT NULL DEFAULT 'mask';
ALTER TABLE repositories MODIFY COLUMN mask VARCHAR(32) NOT NULL DEFAULT 'mask';