---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
# https://www.bluematador.com/blog/an-introduction-to-kubernetes-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis-service
  replicas: 1
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0
        imagePullPolicy: IfNotPresent
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
          name: server-port
        volumeMounts:
        - name: redis-aof
          mountPath: /data
# The PVC is named as volumeClaimTemplate name + pod-name + ordinal number.
  volumeClaimTemplates:
  - metadata:
      name: redis-aof
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 256Mi
  
  # https://zhimin-wen.medium.com/persistent-volume-claim-for-statefulset-8050e396cc51
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: redis
  type: ClusterIP
  clusterIP: None
---